### ISSUE TITLE
v8-changelog: Moved Permanently

### ISSUE THREAD

**Issue by jbcpollak** [rvagg/iojs-tools#4]
I'm not sure if you still support this, but when I try and run v8-changelog, I get this error:

```
$ v8-changelog --range '>=5.0.71.52 <5.0.71.57' --trim                                                                                                                                                       ⏎
/opt/nodes/6.2.1/lib/node_modules/v8-changelog/v8-changelog.js:18
      throw err
      ^

Error: Error from GitHub: Moved Permanently
    at responseHandler (/opt/nodes/6.2.1/lib/node_modules/v8-changelog/node_modules/ghutils/ghutils.js:22:23)
    at BufferList._callback (/opt/nodes/6.2.1/lib/node_modules/v8-changelog/node_modules/jsonist/jsonist.js:25:5)
    at BufferList.end (/opt/nodes/6.2.1/lib/node_modules/v8-changelog/node_modules/jsonist/node_modules/bl/bl.js:83:10)
    at DestroyableTransform.onend (/opt/nodes/6.2.1/lib/node_modules/v8-changelog/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:523:10)
    at DestroyableTransform.g (events.js:286:16)
    at emitNone (events.js:91:20)
    at DestroyableTransform.emit (events.js:185:7)
    at /opt/nodes/6.2.1/lib/node_modules/v8-changelog/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:965:16
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by rvagg** [comment]
fixed by updating a dependency, not for your specific version range as they don't exist as tags on the v8 repo apparently, missing 5.0 and 5.1 it seems.
