### ISSUE TITLE
pr-metadata broken with new update

### ISSUE THREAD

**Issue by jasnell** [rvagg/iojs-tools#5]
Hmm... just landed https://github.com/nodejs/node/commit/cc3a9e79479b9486ba1726889767d44d26bcad81 in Node.js and it appears to have broken pr-metadata...

@Trott @rvagg

```
$ pr-metadata https://github.com/nodejs/node/pull/7975
/usr/local/lib/node_modules/pr-metadata/pr-metadata.js:156
            throw err
            ^

Error: Could not list collaborators from Node.js README
    at BufferList._callback (/usr/local/lib/node_modules/pr-metadata/pr-metadata.js:105:25)
    at BufferList.end (/usr/local/lib/node_modules/pr-metadata/node_modules/bl/bl.js:98:10)
    at DestroyableTransform.onend (/usr/local/lib/node_modules/pr-metadata/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:523:10)
    at DestroyableTransform.g (events.js:273:16)
    at emitNone (events.js:85:20)
    at DestroyableTransform.emit (events.js:179:7)
    at /usr/local/lib/node_modules/pr-metadata/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:965:16
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by Trott** [comment]
Looks like some minor adjustment to a regular expression in `pr-metadata` will fix this...

**Comment by jasnell** [comment]
Yep. Im planning to look at it but I'm on a few other things at the moment
and didn't want to forget about it

**Comment by Trott** [comment]
I'm on it now...
